=== mdht/mdht-models/trunk/generated/org.openhealthtools.mdht.uml.cda.consol/schemas/GreenVitalSigns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated from MDHT UML models. -->
<xsd:schema xmlns="urn:hl7-org:greencda:consol" xmlns:gdt="urn:hl7-org:greencda:datatypes" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:hl7-org:greencda:consol">
	
	<xsd:import namespace="urn:hl7-org:greencda:datatypes" schemaLocation="GreenDatatypes.xsd" />
	
	<!-- ================================================== -->
	<!-- ===== Element Declarations -->
	<!-- ================================================== -->
	<xsd:element name="vitalSign" type="VitalSign" />
	<xsd:element name="vitalSigns" type="VitalSigns" />
	<xsd:element name="vitalSignsOrganizer" type="VitalSignsOrganizer" />
	
	<!-- ================================================== -->
	<!-- ===== Simple Type Definitions -->
	<!-- ================================================== -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- Vital Sign Result -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<xsd:simpleType name="VitalSignResult">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="8310-5" />
			<xsd:enumeration value="8462-4" />
			<xsd:enumeration value="8480-6" />
			<xsd:enumeration value="8287-5" />
			<xsd:enumeration value="8867-4" />
			<xsd:enumeration value="8302-2" />
			<xsd:enumeration value="8306-3" />
			<xsd:enumeration value="2710-2" />
			<xsd:enumeration value="9279-1" />
			<xsd:enumeration value="3141-9" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- ================================================== -->
	<!-- ===== Complex Type Definitions -->
	<!-- ================================================== -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- VitalSign <<cdaTemplate>> -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<xsd:complexType name="VitalSign">
		<xsd:annotation>
			<xsd:documentation>Vital signs are represented as are other results,
				with additional vocabulary constraints.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" name="vitalSignID" type="gdt:InstanceIdentifier" />
			<xsd:element name="vitalSignType" type="VitalSignResult" />
			<xsd:element name="vitalSignDateTime" type="gdt:IntervalOfTimestamps">
				<xsd:annotation>
					<xsd:documentation>Represents the biologically relevant time (e.g.
						time the specimen was obtained from the patient).
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="vitalSignValue" type="gdt:PhysicalQuantity" />
			<xsd:element minOccurs="0" name="interpretationCode" type="gdt:CodedWithEquivalents">
				<xsd:annotation>
					<xsd:documentation>The interpretation code may be present to
						provide an interpretation of the vital signs measure (e.g., High,
						Normal, Low, et cetera).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- VitalSigns <<cdaTemplate>> -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<xsd:complexType name="VitalSigns">
		<xsd:annotation>
			<xsd:documentation>The Vital Signs section contains relevant vital
				signs for the context and use case of the document type, such as
				blood pressure, heart rate, respiratory rate, height, weight, body
				mass index, head circumference, and pulse oximetry. The section
				should include notable vital signs such as the most recent, maximum
				and/or minimum, baseline, or relevant trends.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" name="vitalSignsOrganizer" type="VitalSignsOrganizer" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- VitalSignsOrganizer <<cdaTemplate>> -->
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<xsd:complexType name="VitalSignsOrganizer">
		<xsd:annotation>
			<xsd:documentation>&lt;p&gt;The Vital Signs Organizer groups vital
				signs, which is similar to the Result Organizer, but with further
				constraints. &lt;/p&gt;

				&lt;p&gt;An appropriate nullFlavor can be used when a single result observation
				is contained in the organizer, and organizer/code or organizer/id is
				unknown.&lt;/p&gt;</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="effectiveTime" type="gdt:IntervalOfTimestamps">
				<xsd:annotation>
					<xsd:documentation>represents clinically effective time of the
						measurement, which is most likely when the measurement was
						performed (e.g., a BP measurement).
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" name="vitalSign" type="VitalSign" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== mdht/mdht-models/trunk/generated/org.openhealthtools.mdht.uml.cda.consol/schemas/GreenVitalSigns.xml
<?xml version="1.0" encoding="UTF-8"?>
<vitalSigns xmlns="urn:hl7-org:greencda:consol" xmlns:gdt="urn:hl7-org:greencda:datatypes"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:hl7-org:greencda:consol GreenVitalSigns.xsd ">
	<vitalSignsOrganizer>
		<effectiveTime nullFlavor="NI" />
		<vitalSign>
			<vitalSignID nullFlavor="NI" />
			<!-- <vitalSignType code="8480-6" displayName="Systolic BP" /> -->
			<vitalSignType>8480-6</vitalSignType>
			<vitalSignDateTime nullFlavor="NI" />
			<vitalSignValue value="115" unit="mm[Hg]" />
		</vitalSign>
		<vitalSign>
			<vitalSignID nullFlavor="NI" />
			<!-- <vitalSignType code="8462-4" displayName="Diastolic BP" /> -->
			<vitalSignType>8462-4</vitalSignType>
			<vitalSignDateTime nullFlavor="NI" />
			<vitalSignValue value="70" unit="mm[Hg]" />
		</vitalSign>
		<vitalSign>
			<vitalSignID nullFlavor="NI" />
			<!-- <vitalSignType code="8867-4" displayName="Heart beat" /> -->
			<vitalSignType>8867-4</vitalSignType>
			<vitalSignDateTime nullFlavor="NI" />
			<vitalSignValue value="50" unit="/min" />
		</vitalSign>
	</vitalSignsOrganizer>
</vitalSigns>
